force-app/main/default/objects/Vyuha_Event__e/Vyuha_Event__e.object-meta.xml
<CustomObject>
    <description>Platform Event to manage signaling between Vyhua executions</description>
    <label>Vyuha Event</label>
    <pluralLabel>Vyuha Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Vyuha_Event__e/fields/Apex_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Apex_Job_ID__c</fullName>
    <description>Related Apex Job ID for execution</description>
    <label>Apex Job ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Event related data</description>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vyuha_Event__e/fields/Formation_ID__c.field-meta.xml
<CustomField>
    <fullName>Formation_ID__c</fullName>
    <description>Unique ID for Vyuha Formation ID</description>
    <label>Formation ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Event__e/fields/Schedule_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Item_ID__c</fullName>
    <description>ID for Schedule Item ID if Event was run from the scheduler</description>
    <label>Schedule Item ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Event__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status Code disposition of event</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/vy_EventHandler.cls
// Event Handler
// Interfaces with Signals and Processes 

public class vy_EventHandler implements vy_ExceptionParent {
    
    // primary processor for incoming Events

    public static void process ( List < Vyuha_Event__e > events ) {
        vy_Signal.debugOutput ( 'vy_EventHandler::process', 'events', events );
        // create Signals for each Event
        for ( Vyuha_Event__e event : events ) {
            vy_Signal signal = (vy_Signal) JSON.deserialize ( event.Data__c, vy_Signal.class );
            vy_Signal.debugOutput ( 'vy_EventHandler::process', 'signal', signal );
            signal.initialize ();
            signal.process ();
        }
    }

    public static void create ( vy_Signal signal ) {
        vy_Signal.debugOutput ( 'vy_EventHandler::create', 'signal', signal );
        String jsonStr = JSON.serialize( signal );
        Vyuha_Event__e event = new Vyuha_Event__e ();
        event.data__c = jsonStr;
        event.Apex_Job_ID__c = signal.apexJobId;
        event.Formation_ID__c = signal.formationId;
        event.Schedule_Item_ID__c = signal.scheduleItemId;
        event.Status__c = signal.status;
        Database.SaveResult sr = EventBus.publish ( event );
        if ( sr.isSuccess () == false ) {
            // handle exception
            throw new vy_Exception ( new vy_EventHandler (), 'create event failed' );
        }
        vy_Signal.debugOutput ( 'vy_EventHandler::create', 'event', event );
    }

    public string className () {
        return 'vy_EventHandler';
    }
}