force-app/main/default/objects/Vyuha_Formation__c/Vyuha_Formation__c.object-meta.xml
<CustomObject>
    <description>Definition of Vyuha jobs for scheduling and execution</description>
    <label>Vyuha Formation</label>
    <nameField>
        <label>Vyuha Formation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vyuha Formations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Formation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a Formation is active and runnable</description>
    <inlineHelpText>Indicates if a Formation is active and runnable</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Number of records that each batch should execute - max 9999</description>
    <inlineHelpText>Number of records that each batch should execute - max 9999</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Flow_Input_Variable_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Input_Variable_Name__c</fullName>
    <description>API Field Name on SOQL Query for input into Flow</description>
    <inlineHelpText>API Field Name on SOQL Query for input into Flow</inlineHelpText>
    <label>Flow Input Variable Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Flow_Interview_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_Name__c</fullName>
    <description>Interview Name of Flow to Execute</description>
    <inlineHelpText>Interview Name of Flow to Execute</inlineHelpText>
    <label>Flow Interview Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <description>List of Notification Email addresses (comma delimited)</description>
    <inlineHelpText>List of Notification Email addresses (comma delimited)</inlineHelpText>
    <label>Notification Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Soql_Statement__c.field-meta.xml
<CustomField>
    <fullName>Soql_Statement__c</fullName>
    <description>SOQL Statement to execute and send into Flow - max 4000 characters</description>
    <inlineHelpText>SOQL Statement to execute and send into Flow - max 4000 characters</inlineHelpText>
    <label>Soql Statement</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/Vyuha_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Contains scheduled items for Vyuha which controls how the hourly scheduler interacts with executing Formations</description>
    <label>Vyuha Schedule Item</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vyuha Schedule Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vyuha Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Indicates if Schedule Item is active - inherited from parent Formation</description>
    <formula>Vyuha_Formation__r.Active__c</formula>
    <inlineHelpText>Indicates if Schedule Item is active - inherited from parent Formation</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</description>
    <inlineHelpText>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/One_Time_Datetime__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Datetime__c</fullName>
    <description>Date/Time for single run</description>
    <inlineHelpText>Date/Time for single run</inlineHelpText>
    <label>Run Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Vyuha_Formation__c.field-meta.xml
<CustomField>
    <fullName>Vyuha_Formation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Vyuha Formation for Scheduled Item</description>
    <inlineHelpText>Related Vyuha Formation for Scheduled Item</inlineHelpText>
    <label>Vyuha Formation</label>
    <referenceTo>Vyuha_Formation__c</referenceTo>
    <relationshipLabel>Vyuha Schedule Items</relationshipLabel>
    <relationshipName>Vyuha_Schedule_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/vy_TestDataFactory.cls
// Test Data Factory

public class vy_TestDataFactory {
    
    public static vy_Formation createFormation ( String flowInterviewName, String flowInputVariableName, Boolean active, Integer batchSize, String soqlStatement, String notificationEmail, vy_FlowInterface flowInterface ) {
        Vyuha_Formation__c formation = new Vyuha_Formation__c ();
        formation.Flow_Interview_Name__c = flowInterviewName;
        formation.Flow_Input_Variable_Name__c = flowInputVariableName;
        formation.Active__c = active;
        formation.Batch_Size__c = batchSize;
        formation.Soql_Statement__c = soqlStatement;
        formation.Notification_Email__c = notificationEmail;
        insert formation;

        if ( flowInterface == null ) {
            flowInterface = new vy_FlowInterface ();
        }

        vy_Formation formationObj = new vy_Formation ( flowInterface );
        formationObj.load ( formation.id );
        return formationObj;
    }

    public static vy_ScheduleItem createScheduleItem ( vy_Formation formation, DateTime oneTimeDateTime, String frequency ) {
        Vyuha_Schedule_Item__c scheduleItem = new Vyuha_Schedule_Item__c ();
        scheduleItem.One_Time_DateTime__c = oneTimeDateTime;
        scheduleItem.Frequency__c = frequency;
        scheduleItem.Vyuha_Formation__c = formation.getId ();
        insert scheduleItem;
        vy_ScheduleItem siObject = new vy_ScheduleItem ( formation );
        siObject.load ( scheduleItem.id );
        return siObject;
    }
}