force-app/main/default/objects/Vyuha_Formation__c/Vyuha_Formation__c.object-meta.xml
<CustomObject>
    <description>Definition of Vyuha jobs for scheduling and execution</description>
    <label>Vyuha Formation</label>
    <nameField>
        <label>Vyuha Formation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vyuha Formations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Formation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a Formation is active and runnable</description>
    <inlineHelpText>Indicates if a Formation is active and runnable</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Number of records that each batch should execute - max 9999</description>
    <inlineHelpText>Number of records that each batch should execute - max 9999</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Flow_Input_Variable_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Input_Variable_Name__c</fullName>
    <description>API Field Name on SOQL Query for input into Flow</description>
    <inlineHelpText>API Field Name on SOQL Query for input into Flow</inlineHelpText>
    <label>Flow Input Variable Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Flow_Interview_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_Name__c</fullName>
    <description>Interview Name of Flow to Execute</description>
    <inlineHelpText>Interview Name of Flow to Execute</inlineHelpText>
    <label>Flow Interview Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Soql_Statement__c.field-meta.xml
<CustomField>
    <fullName>Soql_Statement__c</fullName>
    <description>SOQL Statement to execute and send into Flow - max 4000 characters</description>
    <inlineHelpText>SOQL Statement to execute and send into Flow - max 4000 characters</inlineHelpText>
    <label>Soql Statement</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vyuha_Formation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Formation Status</description>
    <inlineHelpText>Formation Status</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/Vyuha_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Contains scheduled items for Vyuha which controls how the hourly scheduler interacts with executing Formations</description>
    <label>Vyuha Schedule Item</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vyuha Schedule Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vyuha Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Indicates if Schedule Item is active - inherited from parent Formation</description>
    <formula>Vyuha_Formation__r.Active__c</formula>
    <inlineHelpText>Indicates if Schedule Item is active - inherited from parent Formation</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</description>
    <inlineHelpText>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Last_Error_Encountered__c.field-meta.xml
<CustomField>
    <fullName>Last_Error_Encountered__c</fullName>
    <description>Date/Time of last error encountered</description>
    <inlineHelpText>Date/Time of last error encountered</inlineHelpText>
    <label>Last Error Encountered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Last_Successful_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Run__c</fullName>
    <description>Date/Time of most recent successful run</description>
    <inlineHelpText>Date/Time of most recent successful run</inlineHelpText>
    <label>Last Successful Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/One_Time_Datetime__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Datetime__c</fullName>
    <description>Date/Time for single run</description>
    <inlineHelpText>Date/Time for single run</inlineHelpText>
    <label>Run Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Schedule Item Status</description>
    <inlineHelpText>Schedule Item Status</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Vyuha_Formation__c.field-meta.xml
<CustomField>
    <fullName>Vyuha_Formation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Vyuha Formation for Scheduled Item</description>
    <inlineHelpText>Related Vyuha Formation for Scheduled Item</inlineHelpText>
    <label>Vyuha Formation</label>
    <referenceTo>Vyuha_Formation__c</referenceTo>
    <relationshipLabel>Vyuha Schedule Items</relationshipLabel>
    <relationshipName>Vyuha_Schedule_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/vy_Scheduler_TEST.cls
@isTest

public class vy_Scheduler_TEST {

    @testSetup
    public static void testSetup () {
        vyuha_Formation__c formation = new vyuha_Formation__c ();
        formation.name                          = 'Test Formation';
        formation.Soql_Statement__c             = 'SELECT ID FROM USER LIMIT 1';
        formation.Flow_Interview_Name__c        = 'Vyuha_Contact_Test';
        formation.Flow_Input_Variable_Name__c   = 'ID';
        formation.batch_size__c                 = 200;
        formation.active__c                     = true;
        formation.status__c                     = 'Sleeping';
        insert formation;
 
        vyuha_Schedule_Item__c scheduleItem = new vyuha_Schedule_Item__c ();
        scheduleItem.Vyuha_Formation__c     = formation.id;
        scheduleItem.Frequency__c           = 'One Time';
        scheduleItem.One_Time_Datetime__c   = Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 );
        scheduleItem.Last_Successful_Run__c = null;
        scheduleItem.status__c              = 'Sleeping';
        insert scheduleItem;

        vyuha_Schedule_Item__c scheduleItem2 = new vyuha_Schedule_Item__c ();
        scheduleItem2.Vyuha_Formation__c     = formation.id;
        scheduleItem2.Frequency__c           = 'One Time';
        scheduleItem2.One_Time_Datetime__c   = Datetime.newInstance ( 2018, 10, 20, 14, 00, 00 );
        scheduleItem2.Last_Successful_Run__c = null;
        scheduleItem2.status__c              = 'Sleeping';
        insert scheduleItem2;
    }
    
    @isTest
    public static void getScheduleItemsToRun_OneTime () {
        Map < String, Object > params = new Map < String, Object > ();
        params.put ( 'now', Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 ));

        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 1, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_TooEarly () {
        Map < String, Object > params = new Map < String, Object > ();
        params.put ( 'now', Datetime.newInstance ( 2018, 09, 20, 13, 00, 00 ));

        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 0, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_LateRun () {
        Map < String, Object > params = new Map < String, Object > ();
        params.put ( 'now', Datetime.newInstance ( 2018, 09, 20, 14, 30, 00 ));

        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 1, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_ParentRunning () {
        Map < String, Object > params = new Map < String, Object > ();
        params.put ( 'now', Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 ));
        // update formation into Running state
        Vyuha_Formation__c formation = [ SELECT ID, Status__c FROM Vyuha_Formation__c ];
        formation.Status__c = 'Running';
        update formation;

        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 0, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_ParentInactive () {
        Map < String, Object > params = new Map < String, Object > ();
        params.put ( 'now', Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 ));
        // update formation into Running state
        Vyuha_Formation__c formation = [ SELECT ID, Active__c FROM Vyuha_Formation__c ];
        formation.Active__c = false;
        update formation;

        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 0, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_AlreadyRun () {
        Map < String, Object > params = new Map < String, Object > ();
        Datetime executionTime = Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 );
        params.put ( 'now', executionTime );
        // update scheduled item to mark a past run
        Vyuha_Schedule_Item__c schedule = [ SELECT Last_Successful_Run__c, ID FROM Vyuha_Schedule_Item__c WHERE One_Time_DateTime__c =: executionTime];
        schedule.Last_Successful_Run__c = executionTime.addDays(-1);
        update schedule;
        // set mock
        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();

        system.assertEquals ( 0, scheduleItems.size ());
    }

    @isTest
    public static void getScheduleItemsToRun_OneTime_AlreadyErrored () {
        Map < String, Object > params = new Map < String, Object > ();
        Datetime executionTime = Datetime.newInstance ( 2018, 09, 20, 14, 00, 00 );
        params.put ( 'now', executionTime );
        // update scheduled item for error in the past
        Vyuha_Schedule_Item__c schedule = [ SELECT Last_Error_Encountered__c, ID FROM Vyuha_Schedule_Item__c WHERE One_Time_DateTime__c =: executionTime];
        schedule.Last_Error_Encountered__c = executionTime.addDays(-1);
        update schedule;
        // set mock
        vy_TimeHelper mockTimeHelper = (vy_TimeHelper) Test.createStub ( vy_TimeHelper.class, new vy_MockService ( params ));

        Test.startTest ();
        vy_Scheduler scheduler = new vy_Scheduler ( mockTimeHelper );
        List < vy_ScheduleItem > scheduleItems = scheduler.getScheduleItemsToRun ();

        Test.stopTest ();
 
        system.assertEquals ( 0, scheduleItems.size ());
    }

}