force-app/main/default/objects/Vyuha_Formation__c/Vyuha_Formation__c.object-meta.xml
<CustomObject>
    <description>Definition of Vyuha jobs for scheduling and execution</description>
    <label>Vyuha Formation</label>
    <nameField>
        <label>Vyuha Formation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vyuha Formations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Formation__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a Formation is active and runnable</description>
    <inlineHelpText>Indicates if a Formation is active and runnable</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/Vyuha_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Contains scheduled items for Vyuha which controls how the hourly scheduler interacts with executing Formations</description>
    <label>Vyuha Schedule Item</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vyuha Schedule Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vyuha Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Indicates if Schedule Item is active - inherited from parent Formation</description>
    <formula>Vyuha_Formation__r.Active__c</formula>
    <inlineHelpText>Indicates if Schedule Item is active - inherited from parent Formation</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</description>
    <inlineHelpText>Select the Frequency for Formation execution.  One Time will run on a specified date/time, Weekly will run recurring based on the date/time selected</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Last_Error_Encountered__c.field-meta.xml
<CustomField>
    <fullName>Last_Error_Encountered__c</fullName>
    <description>Date/Time of last error encountered</description>
    <inlineHelpText>Date/Time of last error encountered</inlineHelpText>
    <label>Last Error Encountered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Last_Successful_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Run__c</fullName>
    <description>Date/Time of most recent successful run</description>
    <inlineHelpText>Date/Time of most recent successful run</inlineHelpText>
    <label>Last Successful Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/One_Time_Datetime__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Datetime__c</fullName>
    <description>Date/Time for single run</description>
    <inlineHelpText>Date/Time for single run</inlineHelpText>
    <label>Run Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vyuha_Schedule_Item__c/fields/Vyuha_Formation__c.field-meta.xml
<CustomField>
    <fullName>Vyuha_Formation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Vyuha Formation for Scheduled Item</description>
    <inlineHelpText>Related Vyuha Formation for Scheduled Item</inlineHelpText>
    <label>Vyuha Formation</label>
    <referenceTo>Vyuha_Formation__c</referenceTo>
    <relationshipLabel>Vyuha Schedule Items</relationshipLabel>
    <relationshipName>Vyuha_Schedule_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/vy_ScheduleItem.cls
// vy_ScheduleItem
// Interface to Scheduled Item

public class vy_ScheduleItem implements vy_ProcessorItem, vy_ExceptionParent {

    private vy_Formation formation;
    private vy_Coordinator coordinator;
    
    public vy_ScheduleItem ( vy_Formation formation, vy_Coordinator coordinator ) {
        this.formation = formation;
        this.coordinator = coordinator;
    }

    public vy_ScheduleItem ( Vyuha_Schedule_Item__c siRecord ) {
        // turn the record into a actual si object
    }

    public void load ( Id recordId ) {

        // query for schedule item
        vyuha_Schedule_Item__c scheduleItem;

        try {
            scheduleItem = [ SELECT ID, Vyuha_Formation__c FROM vyuha_Schedule_Item__c WHERE ID =: recordId ];
            this.formation.load ( scheduleItem.Vyuha_Formation__c );
        } catch ( Exception e ) {
            throw new vy_Exception ( this, e );
        }
    }

    public boolean isValid () {
        return this.formation.isValid ();
    }

    public boolean isRunning () {
        return this.formation.isRunning ();
    }

    public void start () {
        this.formation.start ( this );
    }

    public void complete () {
        this.formation.complete ();
    }

    public string getSoqlStatement () {
        return this.formation.getSoqlStatement ();
    }

    public void execute ( List < sObject > dataList ) {
        this.formation.execute ( dataList );
    }

    // logging

    public void writeLog ( vy_Processor processor ) {
        this.formation.writeLog ( processor );
    }

    public void errorLog ( string errorClass, string errorMessage ) {
        this.formation.errorLog ( errorClass, errorMessage );
    }

    // exception

    public string className () {
        return 'vy_ScheduleItem';
    }

    public static string baseSelectQuery () {
        string soql = '';
        List < string > fields = new List < string > ();
        fields.add ( 'ID' );
        fields.add ( 'Frequency__c' );
        fields.add ( 'Last_Successful_Run__c' );
        fields.add ( 'Last_Error_Encountered__c' );
        fields.add ( 'One_Time_Datetime__c' );
        fields.add ( 'Vyuha_Formation__r.Active__c' );
        fields.add ( 'Vyuha_Formation__c' );
        fields.add ( 'Vyuha_Formation__r.Name' );
        soql += 'SELECT ' + String.join ( fields, ',' );
        soql += ' FROM vyuha_Schedule_Item__c';
        return soql;
    }
}